services:
  postgres:
    image: postgres:latest
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: planetfirst
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  herolib:
    build:
      context: .
      dockerfile: Dockerfile
    image: herolib:latest
    container_name: herolib
    volumes:
      - ~/code:/root/code
    stdin_open: true
    tty: true
    ports:
      - "4100:8100"
      - "4101:8101"
      - "4102:8102"
      - "4379:6379"
      - "4000:3000"
    command: ["/usr/local/bin/ourinit.sh"]
volumes:
  postgres_data:


