[package]
name = "zaz_models"
version = "0.1.0"
edition = "2021"
description = "Rust port of Zaz models"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
