name: Release

on:
  push:
    tags:
      - v*

jobs:
  upload:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            short-name: macos-arm64
          - target: x86_64-apple-darwin
            os: macos-13
            short-name: macos-i64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            short-name: linux-i64

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Vlang
        run: ./install_v.sh --github-actions

      - name: Setup Herolib
        run: ./install_herolib.vsh

      - name: Build Hero
        run: |
          v -w -cg -gc none  -d use_openssl -enable-globals cli/hero.v -o cli/hero-${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: hero-${{ matrix.target }}
          path: cli/hero-${{ matrix.target }}

  release_hero:
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # TODO: this adds commits that don't belong to this branhc, check another action
      # - name: Generate changelog
      #   id: changelog
      #   uses: heinrichreimer/github-changelog-generator-action@v2.3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     headerLabel: "# 📑 Changelog"
      #     breakingLabel: "### 💥 Breaking"
      #     enhancementLabel: "### 🚀 Enhancements"
      #     bugsLabel: "### 🐛 Bug fixes"
      #     securityLabel: "### 🛡️ Security"
      #     issuesLabel: "### 📁 Other issues"
      #     prLabel: "### 📁 Other pull requests"
      #     addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
      #     onlyLastTag: true
      #     issues: false
      #     issuesWoLabels: false
      #     pullRequests: true
      #     prWoLabels: true
      #     author: true
      #     unreleased: true
      #     compareLink: true
      #     stripGeneratorNotice: true
      #     verbose: true

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: cli/bins
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          fail_on_unmatched_files: true
          # body: ${{ steps.changelog.outputs.changelog }}
          files: cli/bins/*
