name: Build Hero on Macos & Run tests

permissions:
  contents: write

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            short-name: macos-arm64
          - target: x86_64-apple-darwin
            os: macos-13
            short-name: macos-i64
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref_name }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Vlang
        run: ./install_v.sh

      - name: Setup Herolib
        run: ./install_herolib.vsh

      - name: Build Hero
        run: |
          v -w -cg -gc none -no-retry-compilation -d use_openssl -enable-globals cli/hero.v

      - name: Do all the basic tests
        run: |
          ./test_basic.vsh
        env:
          LIVEKIT_API_KEY: ${{secrets.LIVEKIT_API_KEY}}
          LIVEKIT_API_SECRET: ${{secrets.LIVEKIT_API_SECRET}}
          LIVEKIT_URL: ${{secrets.LIVEKIT_URL}}
